#??????server:
# ???????
spring:
#  http:
#    encoding:
#      force: true
#      charset: utf-8
#      enabled: true

server:
  tomcat:
    uri-encoding: utf-8
  servlet:
#    context-path: /batch
    encoding:
      charset: UTF-8
      enabled: true
      force: true


